#!/bin/bash
# expand_env.sh
set -e

# Load .env and expand variables
set -a
source .env
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
export ACCOUNT_ID
set +a

# Generate expanded .env
echo "# Autogenerated expanded env file" > .env.generated

# Extract declared variable names from .env and write fully expanded lines
grep -v '^\s*#' .env | grep '=' | while IFS= read -r line; do
  var_name=$(echo "$line" | cut -d= -f1)
  var_value="${!var_name}"
  echo "$var_name=$var_value" >> .env.generated
done
