name: AWS Stack actions

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Makefile target to run'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - update
          - delete
          - logs
          - status
          - outputs
          - events

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
  COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
  COGNITO_REGION: ${{ secrets.COGNITO_REGION }}
  ISSUER_URL: ${{ secrets.ISSUER_URL }}
  PROJECT: ${{ secrets.PROJECT }}
  USER_POOL_ARN: ${{ secrets.USER_POOL_ARN }}
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  API_ENV: ${{ vars.API_ENV }}
  CODE_BUCKET_NAME: ${{ secrets.CODE_BUCKET_NAME }}
  PARAMETERS_FILE: ${{ vars.PARAMETERS_FILE }}
  REGION: ${{ vars.REGION }}
  STACK_NAME: ${{ vars.STACK_NAME }}
  TEMPLATE_FILE: ${{ vars.TEMPLATE_FILE }}

jobs:
  run-make:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # or use a GitHub secret

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y zip jq

      - name: Reconstruct .env
        run: |
          echo "# Generated .env from GitHub Actions env" > .env
          env | grep -E '^(AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY)=' >> .env
          env | grep -E '^(COGNITO_CLIENT_ID|COGNITO_USER_POOL_ID)=' >> .env
          env | grep -E '^(COGNITO_REGION|REGION|ISSUER_URL|PROJECT)=' >> .env
          env | grep -E '^(USER_POOL_ARN|ACCOUNT_ID|API_ENV)=' >> .env
          env | grep -E '^(CODE_BUCKET_NAME|PARAMETERS_FILE)=' >> .env
          env | grep -E '^(STACK_NAME|TEMPLATE_FILE)=' >> .env

      - name: Expand .env
        run: ./expand_env.sh

      - name: Run make target
        run: |
          #set -e  # <- print commands before execution
          export $(grep -v '^#' .env.generated | xargs)
          make  ${{ github.event.inputs.target }}
