name: Run Make Target

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Makefile target to run'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - update
          - delete
          - logs
          - status
          - outputs
          - events

jobs:
  run-make:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # or use a GitHub secret

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y zip jq

      - name: Run make target
        run: |
          make ${{ github.event.inputs.target }}
